function Mask_dilate_erode(binaryEdges,f)

    fig = figure('Position', [50, 50, 1024, 600]);
    ax = axes('Parent', fig);

    % Initialize the mask with the binaryEdges
    processedMask = binaryEdges;

    % Store the sliders' values and the processed mask in UserData
    fig.UserData = struct('ax', ax, 'slider1Value', 10, 'slider2Value', 10, 'processedMask', processedMask);

    % Display the initial mask
    maskViewer(processedMask, f);

    % Create the sliders
    slider1 = uicontrol('Style', 'slider', ...
        'Min', 1, ...
        'Max', 20, ...
        'Value', 1, ...
        'SliderStep', [0.001, 0.1], ...
        'Position', [fig.Position(3) - 200, fig.Position(4) - 30, 200, 20], ...
        'Callback', @(src, event) updateSliceMask(fig, src, 'dilate', f));
    slider2 = uicontrol('Style', 'slider', ...
        'Min', 1, ...
        'Max', 20, ...
        'Value', 1, ...
        'SliderStep', [0.001, 0.1], ...
        'Position', [fig.Position(3) - 200, fig.Position(4) - 60, 200, 20], ...
        'Callback', @(src, event) updateSliceMask(fig, src, 'erode', f));

    % Add labels
    uicontrol('Style', 'text', ...
        'String', 'Dilate', ...
        'Position', [fig.Position(3) - 280, fig.Position(4) - 30, 60, 20], ...
        'HorizontalAlignment', 'left');
    uicontrol('Style', 'text', ...
        'String', 'Erode', ...
        'Position', [fig.Position(3) - 280, fig.Position(4) - 60, 60, 20], ...
        'HorizontalAlignment', 'left');


% keyboard
button = uicontrol('Style', 'pushbutton', ...
        'String', 'Export to workspace', ...
        'Position', [10, fig.Position(4) - 70, 100, 30], ...
        'Callback', @(src, event) ExportMask2Workspace(fig));

while ~evalin('base', 'exist(''Mask'', ''var'')')
    clc
    fprintf('Waiting for the Mask \n')
    pause(1); % Pause to prevent excessive CPU usage
end