function PlotResidField(resid)

% keyboard
fig = figure('Position', [50, 50, 720, 720]);
sliceViewerResid(resid,1,20)
fig.UserData = struct('slider1Value', 1, 'slider2Value', 20);
% Store the axes handle and other necessary data in the figure's UserData
% fig.UserData = struct('ax', ax, 'sliderValue', 1, 'selectedOption', 1);

% Create the slider
slider1 = uicontrol('Style', 'slider', ...
    'Min', 1, ...
    'Max', length(resid), ...
    'Value', 1, ...
    'SliderStep', [1 / (length(resid) - 1), 1 / (length(resid) - 1)], ...
    'Position', [fig.Position(3) - 200, fig.Position(4) - 30, 200, 20], ...
    'Callback', @(src, event) updateSliceResid(fig,src,'slider1', resid));
slider2 = uicontrol('Style', 'slider', ...
    'Min', 1, ...
    'Max', 100, ...
    'Value', 20, ...
    'SliderStep', [0.01, 0.1], ...
    'Position', [fig.Position(3) - 100, fig.Position(4) - 60, 100, 20], ...
    'Callback', @(src, event) updateSliceResid(fig,src,'slider2', resid));
% Text label for Slider 2 value
slider1Label = uicontrol('Style', 'text', ...
    'String', sprintf('%.0f', 1), ...
    'Position', [fig.Position(3) - 230, fig.Position(4) - 30, 20, 20], ...
    'HorizontalAlignment', 'left');
slider2Label = uicontrol('Style', 'text', ...
    'String', sprintf('%.0f', 20), ...
    'Position', [fig.Position(3) - 130, fig.Position(4) - 60, 20, 20], ...
    'HorizontalAlignment', 'left');

% Store the label in the figure for later access
fig.UserData.slider1Label = slider1Label;
fig.UserData.slider2Label = slider2Label;