function [fig,slider,button] = CallInteractive(Mesh,elements,field_names,Field,image,field_name_init)

fig = figure('Position', [50, 50, 720, 720]);
ax = axes('Parent', fig);
sliceViewer(ax, Mesh, Field, elements, image, field_name_init);

% Store the axes handle and other necessary data in the figure's UserData
fig.UserData = struct('ax', ax, 'sliderValue', 1, 'selectedOption', 1);

% Create the slider
slider = uicontrol('Style', 'slider', ...
    'Min', 1, ...
    'Max', length(Field), ...
    'Value', 1, ...
    'SliderStep', [1 / (length(Field) - 1), 1 / (length(Field) - 1)], ...
    'Position', [fig.Position(3) - 200, fig.Position(4) - 30, 200, 20], ...
    'Callback', @(src, event) updateSlice(fig, src, 'slider', Mesh, Field, elements, field_names));
sliderLabel = uicontrol('Style', 'text', ...
    'String', sprintf('%.0f', 1), ...
    'Position', [fig.Position(3) - 230, fig.Position(4) - 30, 20, 20], ...
    'HorizontalAlignment', 'left');
fig.UserData.sliderLabel = sliderLabel;
% Create the dropdown button
% keyboard
if size(Field{1},2) > 2
    if sum(Field{end}(:,3)) == 0
        button = uicontrol('Style', 'popupmenu', ...
            'String', {'E1', 'E2', 'null'}, ...
            'Position', [10, fig.Position(4) - 70, 60, 30], ...
            'Callback', @(src, event) updateSlice(fig, src, 'button', Mesh, Field, elements, field_names));
    else
        button = uicontrol('Style', 'popupmenu', ...
            'String', {'epsxx', 'epsyy', 'epsxy'}, ...
            'Position', [10, fig.Position(4) - 70, 60, 30], ...
            'Callback', @(src, event) updateSlice(fig, src, 'button', Mesh, Field, elements, field_names));
    end
else
    button = uicontrol('Style', 'popupmenu', ...
        'String', {'Ux', 'Uy', 'Magnitude'}, ...
        'Position', [10, fig.Position(4) - 70, 60, 30], ...
        'Callback', @(src, event) updateSlice(fig, src, 'button', Mesh, Field, elements, field_names));
end
end